apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets
  # namespace: eso
spec:
  provider:
    aws:
      service: ParameterStore  
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso   
