apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gmail-smtp-secret
  namespace: monitoring   
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: gmail-smtp-secret   
    creationPolicy: Owner
  data:
    - secretKey: smtp_auth_password
      remoteRef:
        key: /monitoring/gmail-smtp
        property: smtp_auth_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook-secret
  namespace: monitoring
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: slack-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: slack_api_url
      remoteRef:
        key: /monitoring/slack-webhook
        property: slack_api_url
