apiVersion:  apps/v1 
kind: Deployment
metadata:
  name: back-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: back
  template:
    metadata:
      name: api 
      labels:
        tier: back

    spec:
      containers:
        - name: backend
          image: shebl22/backend:6825e1eabcc34824b04dff185811276fa8990339
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: cm-back
            - secretRef:
                name: back-secrets
                
