apiVersion:  apps/v1 
kind: Deployment
metadata:
  name: font-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front
  template:
    metadata:
      name: app 
      labels:
        tier: front

    spec:
      containers:
        - name: frontend
          image: shebl22/frontend:10b95b15ab60445bb907b053606851f15e3fde98
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: cm-front
