apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: shebl22.me
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb
  rules:
  - host: shebl22.me
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: back-svc
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-svc
            port:
              number: 80
