# roles/minikube/tasks/main.yml
- name: Check if Minikube is installed
  ansible.builtin.command:
    cmd: minikube version
  register: minikube_check
  failed_when: false
  changed_when: false

- name: Install Minikube if not present
  when: minikube_check.rc != 0
  become: true
  block:
    - name: Download and install Minikube
      ansible.builtin.shell: |
        curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
        rm minikube-linux-amd64
      args:
        creates: /usr/local/bin/minikube

- name: Check if minikube is running
  ansible.builtin.shell:
    cmd: minikube status
  register: minikube_status
  become_user: "{{ansible_user}}"
  become: false
  failed_when: false
  changed_when: false

- name: Start Minikube if not running
  ansible.builtin.shell: |
    minikube start --driver=docker --memory=3600 --cpus=2 --wait=all --force
  become_user: "{{ ansible_user}}"
  become: false
  environment:
    HOME: "/home/{{ ansible_user}}"
  when: "'host: Running' not in minikube_status.stdout"

- name: Wait for Kubernetes API to be ready
  ansible.builtin.shell: kubectl get nodes
  register: kube_ready
  retries: 10
  delay: 15
  until: kube_ready.rc == 0
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: enable ingress
  ansible.builtin.shell:
    cmd: minikube addons enable ingress 

- name: Ensure kubeconfig exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube/config
    state: file
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Export KUBECONFIG in bashrc for future sessions
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
    create: yes

- name: Read Minikube CA certificate
  slurp:
    src: /home/ubuntu/.minikube/ca.crt
  register: ca_crt

- name: Read Minikube client certificate
  slurp:
    src: /home/ubuntu/.minikube/profiles/minikube/client.crt
  register: client_crt

- name: Read Minikube client key
  slurp:
    src: /home/ubuntu/.minikube/profiles/minikube/client.key
  register: client_key

- name: Generate portable kubeconfig with embedded certs
  copy:
    dest: /home/ubuntu/kubeconfig-portable.yaml
    content: |
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: {{ ca_crt.content }}
          server: https://192.168.49.2:8443
        name: minikube
      contexts:
      - context:
          cluster: minikube
          namespace: default
          user: minikube
        name: minikube
      current-context: minikube
      kind: Config
      preferences: {}
      users:
      - name: minikube
        user:
          client-certificate-data: {{ client_crt.content }}
          client-key-data: {{ client_key.content }}

- name: Fetch kubeconfig to local machine
  fetch:
    src: /home/ubuntu/kubeconfig-portable.yaml
    dest: "../Terraform/kubeconfig"
    flat: yes

- name: Display Minikube status
  ansible.builtin.debug:
    msg: >-
      Minikube is {{ 'already installed' if minikube_check.rc == 0 else 'newly installed' }} and cluster started
