# docker-compose.yaml

services:
  # Nginx Reverse Proxy (Replaces Kubernetes Ingress)
  nginx:
    image: nginx:1.28-alpine3.21-otel
    container_name: islamic-app-proxy
    ports:
      - "8090:80" # Main entry point for the app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - islamic-network
    depends_on:
      - frontend
      - backend

  # Database Tier (No changes needed)
  database:
    image: postgres:17.5
    container_name: islamic-app-db
    restart: always
    environment:
      POSTGRES_DB: islamic_app
      POSTGRES_USER: islamic_user
      POSTGRES_PASSWORD: islamic_pass123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - islamic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U islamic_user -d islamic_app"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Tier
  backend:
    build:
      context: ./backend
    container_name: islamic-app-backend
    restart: always
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://islamic_user:islamic_pass123@database:5432/islamic_app
      SECRET_KEY: your-super-secret-key-change-in-production
      JWT_SECRET_KEY: your-jwt-secret-key-change-in-production
      CORS_ORIGINS: http://localhost,http://nginx,http://localhost:8090
    # Port 5000 is now optional for direct API testing, not required by the app itself
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - islamic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Tier
  frontend:
    build:
      context: ./frontend
        
    container_name: islamic-app-frontend
    restart: always
    environment:
       REACT_APP_API_URL: /api
    depends_on:
      - backend
    networks:
      - islamic-network

networks:
  islamic-network:
    driver: bridge

volumes:
  postgres_data: